### PR TITLE
de-fix-messenger.dtd

### PR DESCRIPTION
**Pull request by mediamr**
de-fix-messenger.dtd

### CODE REVIEW

**Comment by shermandickman** [comment]
@mediamr You may wish to hold off on future translations, as we have a massive change to the branch coming up. A huge DE translation project that is about to land!

**Comment by shermandickman** [comment]
@mediamr  After 5.0 ships next week, we would welcome PR requests to address issues with DE at that time.  We'll then push out DE corrections in 5.0.1, 5.0.2, etc. which we anticipate will be quite frequent now.

**Comment by mediamr** [comment]
Ok. Sorry. I will wait until 5.0 is out

**Comment by shermandickman** [comment]
@mediamr No need to be sorry!  We would appreciate any feedback you have after 5.0!!!

**Pull request closed without merging**
