### PR TITLE
Merge remote-tracking branch 'refs/remotes/postbox/master'

### PR DESCRIPTION
**Pull request by LBinary**

### CODE REVIEW

**Comment by shermandickman** [comment]
@mkaply Do you know what this is?   We have localizers starting to jump in on the localization branch, but I'm not sure what this is exactly, or who LBinary is.

**Comment by LBinary** [comment]
Sherman,


FYI: LBinary is my username.

Greetings,

Klaas

________________________________
Van: Sherman Dickman <notifications@github.com>
Verzonden: maandag 15 augustus 2016 17:26
Aan: postbox/localizations
CC: LBinary; Author
Onderwerp: Re: [postbox/localizations] Merge remote-tracking branch 'refs/remotes/postbox/master' (#17)


@mkaply<https://github.com/mkaply> Do you know what this is? We have localizers starting to jump in on the localization branch, but I'm not sure what this is exactly, or who LBinary is.

-

**Comment by mkaply** [comment]
I don't understand what this. There are no actual code changes here, so there is nothing to merge...

**Comment by shermandickman** [comment]
Closing, as it appears that nothing changed.

**Pull request closed without merging**
